# Generated by Django 4.2.4 on 2023-10-06 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_tipopago_alter_ventas_options_ventas_cliente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipopago',
            options={'verbose_name': 'tipopago', 'verbose_name_plural': 'tipopagos'},
        ),
    ]
