# Generated by Django 4.2.4 on 2023-10-06 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_detallecompra_total_alter_detallecompra_cantidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='precio_unitario_compra',
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='precio_unitario_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
