# Generated by Django 4.2.4 on 2023-10-07 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_remove_compra_precio_unitario_compra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
    ]
