# Generated by Django 4.2.4 on 2023-10-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compra_options_remove_compra_cantidad_and_more'),
        ('proveedores', '0003_alter_proveedores_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoProveedor',
        ),
    ]
